apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitorning-shell-expoter
    app.kubernetes.io/name: monitorning-shell-expoter
  name: monitorning-shell-expoter
  namespace: monitorning
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: monitorning-shell-expoter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monitorning-shell-expoter
        app.kubernetes.io/name: monitorning-shell-expoter
    spec:
      containers:
      - env:
        - name: LISTEN_PORT
          value: "9592"
        - name: SCRIPTS_PATH
          value: /scripts
        - name: INTERVAL
          value: "60"
        - name: RACK_EXECL_PATH
          value: "/tmp"
        image: 10.29.208.125/daocloud/shell-exporter:v0.19
        imagePullPolicy: IfNotPresent
        name: shell-expoter
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: scripts-volume
        - mountPath: /tmp
          name: rack-execl-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 429
          name: shell-expoter-scripts
        name: scripts-volume
      - configMap:
          defaultMode: 429
          name: rack-number.xlsx
        name: rack-execl-volume
