apiVersion: v1
kind: Service
metadata:
  annotations:
    daocloud.io/component: monitorning
  creationTimestamp: "2023-09-24T14:16:01Z"
  labels:
    app: monitorning-shell-expoter
    app.kubernetes.io/name: monitorning-shell-expoter
    release: monitorning
  name: monitorning-shell-expoter
  namespace: monitorning
spec:
  ipFamily: IPv4
  ports:
  - name: metrics
    port: 9592
    protocol: TCP
    targetPort: 9592
  selector:
    app: monitorning-shell-expoter
  sessionAffinity: None
  type: ClusterIP
