apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: monitorning-shell-expoter
    release: monitorning
  name: monitorning-shell-expoter
  namespace: monitorning
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - monitorning
  selector:
    matchLabels:
      app: monitorning-shell-expoter
